name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.0
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager
      
      - name: Scan for known security vulnerabilities in gems used
        run: bin/bundler-audit --ignore CVE-2026-33658
      
  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.0
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    env:
      RUBOCOP_CACHE_ROOT: tmp/rubocop
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.0
          bundler-cache: true

      - name: Security audit dependencies
        run: bundle exec bundle audit --update --ignore CVE-2026-33658
      - name: Security audit applicate code
        run: bundle exec brakeman -q -w2
      - name: Lint code for consistent style in Ruby files
        run: bundle exec rubocop --parallel

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

      # redis:
      #   image: valkey/valkey:8
      #   ports:
      #     - 6379:6379
      #   options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libpq-dev

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.0
          bundler-cache: true
      - name: Remove cached gems
        run: rm -rf vendor/bundle
      - name: Install gems
        run: bundle config set force_ruby_platform true && bundle install

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
          # RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          # REDIS_URL: redis://localhost:6379/0
        run: bin/rails db:test:prepare test

  system-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16
        env:
          POSTGRES_USER: vivek
          POSTGRES_PASSWORD: password
          POSTGRES_DB: task_app_test
        ports: ['5432:5432']
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
    #   postgres:
    #     image: postgres
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #     ports:
    #       - 5432:5432
    #     options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

      # redis:
      #   image: valkey/valkey:8
      #   ports:
      #     - 6379:6379
      #   options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v6

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.0
          bundler-cache: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Start Postgres
        run: sudo service postgresql start

      - name: Setup Database
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://vivek:password@localhost:5432/task_app_test
        run: bin/rails db:create db:migrate

      - name: Run System Tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://vivek:@localhost:5432/task_app_test
        run: bin/rails test
